### ISSUE TITLE
Configuration of the lib

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor-lib#16]
Goal: We need to be able to persist the configuration of the lib used during the creation of the data. 
This is needed when we'll need to retrieve the data back.

Requirements:
- The configuration should contain all the configuration of each component
- Configuration should be serializable in a compact format, so we can save it in the metadata server easily without consuming too much storage.
- From the configuration, the library knows how to do to put/get data out of the 0-stor. This is the only input the lib needs.

**Comment by iwanbk** [comment]
> Configuration should be serializable in a compact format, so we can save it in the metadata server easily without consuming too much storage.


> From the configuration, the library knows how to do to put/get data out of the 0-stor. This is the only input the lib needs.

Although use morre storage, i suggest to use yaml instead of capnp.
the configuration would be like this
```yaml
name: client
pipes:
   - name: pipe1
     type : compress
     configs:
          field1: ..
          field2: ...
   - name: pipe2
     type : encrypt
     configs:
          field1: ..
          field2: ..
```
`configs` there is `map[string]interface`, when we see `compress` then we `cast` that `map[string]interface{}` to `compress.Config`
